#!/usr/bin/env python3
"""
Generates the viewer's bundled sample document.

Written by hand rather than with a PDF library so the repo needs no extra build
dependency to reproduce it. The output deliberately exercises the features the
viewer implements: real (selectable, searchable) text so the text layer and
search have something to bind to, and several pages so paging and scroll work.
"""
import zlib
from pathlib import Path

# Rendered with the Type1 base-14 fonts, which every PDF reader has built in —
# no font embedding, so the file stays small and fully self-contained.
PAGES = [
    ("PDF Viewer", [
        ("H", "PDF Viewer"),
        ("P", "A sample document, generated for this repository."),
        ("P", "It carries no third-party content: every page here exists"),
        ("P", "to exercise the viewer itself."),
        ("S", "What to try"),
        ("P", "Select text with the cursor, then pick Highlight,"),
        ("P", "Underline or Strikeout from the Annotate row."),
        ("P", "Use the search field to jump between matches."),
        ("P", "Press T to place a text box, then drag it or"),
        ("P", "pull its right edge to rewrap the words inside."),
    ]),
    ("Annotation tools", [
        ("H", "Annotation tools"),
        ("S", "Highlight, underline, strikeout"),
        ("P", "These three act on a text selection. Select a phrase"),
        ("P", "on this page and apply one; the mark is stored against"),
        ("P", "the page in normalized coordinates, so it stays put"),
        ("P", "when the document is zoomed."),
        ("S", "Pen"),
        ("P", "The pen draws freehand strokes onto an overlay above"),
        ("P", "the page. Strokes keep their shape across zoom levels."),
        ("S", "Text"),
        ("P", "A text box is placed where you click. It can be moved,"),
        ("P", "resized, recolored and resized in type."),
    ]),
    ("Search and navigation", [
        ("H", "Search and navigation"),
        ("P", "The word compiler appears on this page several times."),
        ("P", "A compiler translates source code into another form."),
        ("P", "A just-in-time compiler does that work while the"),
        ("P", "program is already running."),
        ("S", "Paging"),
        ("P", "Use the arrows in the toolbar to step between pages,"),
        ("P", "or scroll continuously. The page indicator on the"),
        ("P", "right reports the current position."),
        ("S", "Zoom"),
        ("P", "Zoom with the toolbar controls or a trackpad pinch."),
        ("P", "Annotations are re-laid out to match."),
    ]),
    ("About this file", [
        ("H", "About this file"),
        ("P", "This document is generated by a script in the"),
        ("P", "repository, not copied from anywhere. It is placed"),
        ("P", "in the public domain along with the rest of the"),
        ("P", "project."),
        ("S", "Regenerating"),
        ("P", "Run the generator to rebuild this file. Edit the"),
        ("P", "PAGES table in that script to change the contents."),
    ]),
]


def esc(s: str) -> str:
    return s.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def content_stream(blocks) -> bytes:
    """Lays a page out top-down, choosing size and leading per block kind."""
    out = ["BT"]
    y = 742
    for kind, text in blocks:
        if kind == "H":
            out.append(f"/F2 24 Tf 1 0 0 1 72 {y} Tm ({esc(text)}) Tj")
            y -= 42
        elif kind == "S":
            y -= 8
            out.append(f"/F2 13 Tf 1 0 0 1 72 {y} Tm ({esc(text)}) Tj")
            y -= 24
        else:
            out.append(f"/F1 11 Tf 1 0 0 1 72 {y} Tm ({esc(text)}) Tj")
            y -= 17
    out.append("ET")
    return zlib.compress("\n".join(out).encode("latin-1"))


def build() -> bytes:
    objs: list[bytes] = []

    def add(b: bytes) -> int:
        objs.append(b)
        return len(objs)  # object numbers are 1-based

    font_regular = add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica "
                       b"/Encoding /WinAnsiEncoding >>")
    font_bold = add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold "
                    b"/Encoding /WinAnsiEncoding >>")

    # The pages tree must know its children before they exist, so its object
    # number is reserved here and its body is written once the ids are known.
    pages_id = add(b"")

    page_ids = []
    for _title, blocks in PAGES:
        data = content_stream(blocks)
        stream_id = add(b"<< /Length %d /Filter /FlateDecode >>\nstream\n" % len(data)
                        + data + b"\nendstream")
        page_ids.append(add(
            b"<< /Type /Page /Parent %d 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /F1 %d 0 R /F2 %d 0 R >> >> "
            b"/Contents %d 0 R >>" % (pages_id, font_regular, font_bold, stream_id)))

    kids = b" ".join(b"%d 0 R" % i for i in page_ids)
    objs[pages_id - 1] = (b"<< /Type /Pages /Count %d /Kids [%s] >>"
                          % (len(page_ids), kids))

    catalog = add(b"<< /Type /Catalog /Pages %d 0 R >>" % pages_id)
    info = add(b"<< /Title (PDF Viewer \\226 Sample Document) "
               b"/Producer (tools/make-sample-pdf.py) >>")

    # Serialize, recording each object's byte offset for the xref table.
    buf = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = []
    for n, body in enumerate(objs, start=1):
        offsets.append(len(buf))
        buf += b"%d 0 obj\n" % n + body + b"\nendobj\n"

    xref_at = len(buf)
    buf += b"xref\n0 %d\n" % (len(objs) + 1)
    buf += b"0000000000 65535 f \n"
    for off in offsets:
        buf += b"%010d 00000 n \n" % off
    buf += (b"trailer\n<< /Size %d /Root %d 0 R /Info %d 0 R >>\nstartxref\n%d\n%%%%EOF\n"
            % (len(objs) + 1, catalog, info, xref_at))
    return bytes(buf)


if __name__ == "__main__":
    # The viewer document loads ./sample.pdf relative to itself, so the file
    # belongs beside viewer.html rather than next to this script.
    dest = Path(__file__).resolve().parent.parent / "packages/viewer/src/sample.pdf"
    out = build()
    dest.write_bytes(out)
    print(f"wrote {dest} ({len(out):,} bytes, {len(PAGES)} pages)")
